version: "3"
services:

    callinker:
        image: qikcik/callinker:latest
        network_mode: "host"
        ports:
            - "7777:7777"
            - "5038:5038"

        restart: on-failure
        environment:
            - BASELINKERAPI=1002128-1009562-GVHRM76JKHM5X1KWX8D8WHYKTTINFYFS3KF9ERY7AXUSCJ3FPQ8H8D6SCMROS54N
            - AMILOGIN=callinker
            - AMIPASSWORD=1234
            - AMIADRESS=192.168.1.2
        
        labels:
            - com.centurylinklabs.watchtower.enable=true

    watchtower:
        image: containrrr/watchtower
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        command: --cleanup --interval 10 --label-enable

        environment:
            - REPO_USER=qikcik
            - REPO_PASSWORD=haslo1234