version: "3"
services:




    callinker:
        image: qikcik/callinker:latest
        ports:
            - "7777:80"
            - "5038:5038"

        restart: on-failure
        environment:
            - BASELINKERAPI=1002128-1009562-GVHRM76JKHM5X1KWX8D8WHYKTTINFYFS3KF9ERY7AXUSCJ3FPQ8H8D6SCMROS54N
            - AMILOGIN=callinker
            - AMIPASSWORD=1234
            - AMIADRESS=192.168.1.2
            - AMIPORT=5038
            - WEBPORT=7777
        
        labels:
            - com.centurylinklabs.watchtower.enable=true

    watchtower:
        image: containrrr/watchtower
        volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /root/.docker/config.json:/config.json
        command: --cleanup --interval 300 --label-enable

        environment:
            - REPO_USER=qikcik
            - REPO_PASSWORD=haslo1234